import type { Metadata } from "next"
import { Work_Sans } from "next/font/google"
import "./styles/globals.css"
import "./styles/home.css"
import "./styles/decorations.css"

import { AppProvider } from "@/providers/app-provider"
import { Toaster } from "sonner"

const font = Work_Sans({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
})

export const metadata: Metadata = {
    title: "NIR",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html
            className="h-full w-full overflow-y-hidden"
            lang="en"
            suppressHydrationWarning
        >
            <body
                className={`${font.className} h-full w-full bg-background`}
                suppressHydrationWarning
            >
                <AppProvider>
                    {children}
                    <Toaster richColors />
                </AppProvider>
            </body>
        </html>
    )
}
